-- Public pet discovery must not become a claim/match-progress oracle.
-- V1 exposes only the opaque case id, LOST/FOUND partition and display name.
-- The signed photo URL is generated by the API only after separate human moderation.
CREATE OR REPLACE VIEW public_pet_cases AS
SELECT
  c.public_id,
  c.kind,
  c.public_name
FROM pet_cases c
WHERE c.status IN ('OPEN','MATCH_REVIEW');
