'use client';
import { useState } from 'react';
const API=process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:3001/api/v1';

export default function OtpLogin({audience,onAuthenticated}:{audience:'CITIZEN'|'OFFICIAL';onAuthenticated:()=>void}){
  const [phone,setPhone]=useState(''); const [code,setCode]=useState(''); const [flow,setFlow]=useState(''); const [session,setSession]=useState(''); const [msg,setMsg]=useState(''); const [busy,setBusy]=useState(false);
  async function request(){setBusy(true);setMsg('');try{const r=await fetch(`${API}/auth/otp/request`,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({phone,audience})});const j=await r.json();if(!r.ok)throw new Error(Array.isArray(j.message)?j.message.join(', '):j.message||'No fue posible enviar el código');setFlow(j.flow);setSession(j.session||'');setMsg('Código enviado por SMS.');}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
  async function verify(){setBusy(true);setMsg('');try{const r=await fetch(`${API}/auth/otp/verify`,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({phone,audience,flow,session:session||undefined,code})});const j=await r.json();if(!r.ok)throw new Error(Array.isArray(j.message)?j.message.join(', '):j.message||'Código inválido');onAuthenticated();}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
  return <div className="card auth-card"><h2>Acceso sin contraseña</h2><p className="muted">Ingresa tu celular. Recibirás un código OTP por SMS.</p><label>Número celular</label><input inputMode="tel" placeholder="3001234567" value={phone} onChange={e=>setPhone(e.target.value)}/>{!flow?<button className="btn primary" disabled={busy||!phone} onClick={request}>{busy?'Enviando…':'Enviar código'}</button>:<><label>Código OTP</label><input inputMode="numeric" autoComplete="one-time-code" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))}/><div className="row"><button className="btn primary" disabled={busy||code.length<4} onClick={verify}>{busy?'Verificando…':'Ingresar'}</button><button className="btn secondary" disabled={busy} onClick={()=>{setFlow('');setCode('')}}>Cambiar número</button></div></>}{msg&&<p className="alert">{msg}</p>}</div>
}
